let productsDB = [
    {
    id :1,
    title:"Airpod",
    size:"large",
    imageUrl:"img/Airpods.jpg",
    des:"All‑Screen Liquid Retina Display mit ProMotion, True Tone und großem P3 Farbraum",
    qty:1,
    isMe:"N",
},
{
    id :2,
    title:"laptop",
    size:"small",
    imageUrl:"img/laptop.jpg",
    des:"All‑Screen Liquid Retina Display mit ProMotion, True Tone und großem P3 Farbraum",
    qty:1,
    isMe:"N",
},
{
    id :3,
    title:"watch",
    size:"small",
    imageUrl:"img/watch.jpg",
    des:"All‑Screen Liquid Retina Display mit ProMotion, True Tone und großem P3 Farbraum",
    qty:1,
    isMe:"N",
},
{
    id :4,
    title:"iphone",
    size:"medium",
    imageUrl:"img/iphon.jpg",
    des:"All‑Screen Liquid Retina Display mit ProMotion, True Tone und großem P3 Farbraum",
    qty:1,
    isMe:"N",
},
{
    id :5,
    title:"headphones",
    size:"small",
    imageUrl:"img/headphones.jpg",
    des:"All‑Screen Liquid Retina Display mit ProMotion, True Tone und großem P3 Farbraum",
    qty:1,
    isMe:"N",
},
{
    id :6,
    title:" ipad Pro",
    size:"12,9",
    imageUrl:"img/apple-ipad-pro.png",
    des:"All‑Screen Liquid Retina Display mit ProMotion, True Tone und großem P3 Farbraum",
    qty:1,
    isMe:"N",
},
];
// localStorage.setItem("products",JSON.stringify(productsDB));